<?php
include 'db.php';

if ($_SERVER['REQUEST_METHOD'] == 'POST') {
    // Personal Information
    $lastname = strtoupper($_POST['lastname']);
    $firstname = strtoupper($_POST['firstname']);
    $extensionname = strtoupper($_POST['extensionname']);
    $middleinitial = strtoupper($_POST['middleinitial']);
    $dob = date('Y-m-d', strtotime($_POST['dob']));

    // Insert into applicants table
    $sql_applicant = "INSERT INTO applicants (lastname, firstname, extensionname, middleinitial, dob) 
                      VALUES ('$lastname', '$firstname', '$extensionname', '$middleinitial', '$dob')";

    if ($conn->query($sql_applicant) === TRUE) {
        $applicant_id = $conn->insert_id;

        // Exam Details
        $dateofexam = $_POST['dateofexam'];
        $typeofexam = $_POST['typeofexam'];
        $regioncode = $_POST['regioncode'];
        $agree = isset($_POST['agree']) ? 'Y' : 'N';

        // Insert into exam_details table
        $sql_exam = "INSERT INTO exam_details (applicant_id, dateofexam, typeofexam, regioncode, consent_agreed) 
                     VALUES ('$applicant_id', '$dateofexam', '$typeofexam', '$regioncode', '$agree')";

        if ($conn->query($sql_exam) === TRUE) {
            echo "<script>alert('Application successfully submitted!'); window.location.href='index.html';</script>";
        } else {
            echo "Error: " . $sql_exam . "<br>" . $conn->error;
        }
    } else {
        echo "Error: " . $sql_applicant . "<br>" . $conn->error;
    }

    $conn->close();
} else {
    header('Location: index.html');
    exit();
}
?>
<?php
require('pdf/tcpdf.php'); // or use fpdf.php if using FPDF

// Capture form data
$lastname = strtoupper($_POST['lastname']);
$firstname = strtoupper($_POST['firstname']);
$extensionname = strtoupper($_POST['extensionname']);
$middleinitial = strtoupper($_POST['middleinitial']);
$dob = $_POST['dob'];
$dateofexam = $_POST['dateofexam'];
$typeofexam = $_POST['typeofexam'];
$regioncode = $_POST['regioncode'];

// Create new PDF document
$pdf = new TCPDF('P', 'mm', 'A4', true, 'UTF-8', false);
$pdf->SetTitle('OCSERGS Exam Result');
$pdf->AddPage();

// Add header
$pdf->SetFont('Helvetica', 'B', 16);
$pdf->Cell(190, 10, 'ONLINE CAREER SERVICE EXAM RESULT', 0, 1, 'C');
$pdf->SetFont('Helvetica', '', 12);
$pdf->Cell(190, 5, 'Generated by OCSERGS', 0, 1, 'C');
$pdf->Ln(10);

// Add applicant details
$pdf->SetFont('Helvetica', '', 12);
$pdf->Cell(0, 10, "Applicant's Personal Information", 0, 1, 'L');
$pdf->SetFont('Helvetica', '', 10);
$pdf->Cell(0, 7, "Last Name: $lastname", 0, 1);
$pdf->Cell(0, 7, "First Name: $firstname", 0, 1);
$pdf->Cell(0, 7, "Extension Name: $extensionname", 0, 1);
$pdf->Cell(0, 7, "Middle Initial: $middleinitial", 0, 1);
$pdf->Cell(0, 7, "Date of Birth: $dob", 0, 1);
$pdf->Ln(5);

// Add exam details
$pdf->SetFont('Helvetica', '', 12);
$pdf->Cell(0, 10, "Details of Examination", 0, 1, 'L');
$pdf->SetFont('Helvetica', '', 10);
$pdf->Cell(0, 7, "Date of Examination: $dateofexam", 0, 1);
$pdf->Cell(0, 7, "Type of Examination: $typeofexam", 0, 1);
$pdf->Cell(0, 7, "CSC Office: $regioncode", 0, 1);
$pdf->Ln(10);

// Add thank you message
$pdf->SetFont('Helvetica', 'I', 10);
$pdf->Cell(0, 7, "Thank you for using OCSERGS. Download and keep this result for reference.", 0, 1, 'C');

// Save and output the PDF
$pdf->Output('exam_result.pdf', 'D'); // 'D' forces download
?>
 
